Use dynamic manifest
built-on-openfin/container-starter pull request #15
Opened 2022-03-02 18:27 UTC by pjsm41390

Dynamic manifests to launch different apps with different manifests. 

Still need update the read me etc. but core functionality is there.

2022-03-03 12:50 UTC, johnman requested changes
Looks good. Just a few changes (e.g. removing stuff that isn't needed and moving the sample to the root) but thanks for doing this!

2022-03-03 12:50 UTC, johnman commented on how-to/use-dynamic-manifest/basic/README.md
> +# Use Preloads Hello World
Hi,

I know you mentioned this but just adding it here as well.

Can this be updated to reflect the sample? Can we also move the example out of the basic folder so it is in the root of use-dynamic-manifest? It is in a subfolder for preload because we have multiple preload examples inside. I think this one will just be specific to dynamic manifests.

2022-03-03 12:50 UTC, johnman commented on how-to/use-dynamic-manifest/basic/client/src/app.ts
> +import { fin } from "openfin-adapter/src/mock";
I think we could get away with not needing a client folder for this sample. We can delete the client and remove build-client from the npm scripts and just have the public folder with the three static index.html pages. This way npm run build only builds the server and the focus stays on the server aspect of this sample.

2022-03-03 12:50 UTC, johnman commented on how-to/use-dynamic-manifest/basic/package.json
> +    "build-client": "webpack build --config ./client/webpack.config.js --mode=development",
We can remove build-client and update line 7 so it only runs build-server

2022-03-03 12:50 UTC, johnman commented on how-to/use-dynamic-manifest/basic/package.json
> +    "client": "start fin://localhost:8080/config/platform.config.json",
could we have client and also point to the dynamic manifest (i.e. if no params then it is the default manifest)? That way it shows there is only ever the server generated version.

2022-03-03 12:50 UTC, johnman commented on how-to/use-dynamic-manifest/basic/package.json
> +    "dev" :"start fin://localhost:8080/?env=dev",
could this be /manifest?env=dev so it is a bit clearer that it is a manifest path rather than root?

2022-03-03 12:50 UTC, johnman commented on how-to/use-dynamic-manifest/basic/public/html/app-dev.html
> +    <script src="../js/app.bundle.js"></script>
These pages in the public folder could do away with the script tag and the buttons.

That way the html page could simply say You are currently looking at the dev environment, you are currently looking at staging, prod etc.

We can then skip the js as we are showing that a server can return a dynamic manifest (and in this case it is simply changing the landing page but could do anything really).

2022-03-03 12:50 UTC, johnman commented on how-to/use-dynamic-manifest/basic/public/html/app-dev.html
> +    <title>Hello dunamic World</title>
Sight update dunamic -> dynamic.

2022-03-03 12:50 UTC, johnman commented on how-to/use-dynamic-manifest/basic/public/html/app-staging.html
> +    <title>Hello dunamic World</title>
Same comments as app-dev.html

2022-03-03 12:50 UTC, johnman commented on how-to/use-dynamic-manifest/basic/server/src/index.ts
> +//app.use(express.static(path.join(__dirname, '../../public')));
Haven't tried this but is it possible to keep app.use for static file support in public and then have one entry for app.get('/manifest' ?

2022-03-03 12:50 UTC, johnman commented on how-to/use-dynamic-manifest/basic/server/src/index.ts
> +   if(env === 'dev'){
Can we have a template e.g. let manifest = json object goes here.

Then the env switch would be something like:

switch(env) {

case "dev": {

manifest.snapshot.windows[0].layout.content[0].content[0].componentState.url = "http://localhost:8080/html/app-dev.html"
break;
}
case "staging": {
manifest.snapshot.windows[0].layout.content[0].content[0].componentState.url = "http://localhost:8080/html/app-staging.html"
break;
}
default: {
// nothing happens and the default manifest that loads the prod html page is going to be returned
}

res.json(manifest);

2022-03-03 16:59 UTC, pjsm41390 commented on how-to/use-dynamic-manifest/basic/server/src/index.ts
> +   if(env === 'dev'){
I'llchange to switch after.

2022-03-04 17:50 UTC, johnman approved these changes

2022-03-04 17:51 UTC, merged