Dev/adam/add analytics to your application
built-on-openfin/container-starter pull request #18
Opened 2022-03-29 16:35 UTC by adam-saland

- [x] Replace Current images with gifs.
- [x] Move OpenFin.md and ElasticSearch.md into README.md.
- [x] Update README.md to reflect correct build scripts.
- [x] Create a directory for dockerized "full" version and Move contents of current repo to dockerized "full" version.
- [x] Copy contents from current repo to "basic" directory without docker / es / kibana.
- [x] Create a view that displays a log of payloads sent from app monitor.

2022-03-29 16:37 UTC, adam-saland commented
- [ ] remove how-to/launch-external-process from this PR

2022-04-14 09:00 UTC, obany requested changes
A few fixes and updates

2022-04-14 09:04 UTC, obany commented on how-to/use-launch-external-process/public/index.html
> +        <img src="assets/logo.svg">
This asset doesn't exist

2022-04-14 10:56 UTC, johnman commented on how-to/add-analytics-to-your-application/basic/package.json
> +  "author": "Phil Vogt",
This code was originally written by Phil but Adam has updated it and got it in working order for the container. But yeah worth Adam updating the auther.

2022-04-14 11:11 UTC, johnman requested changes

2022-04-14 11:11 UTC, johnman commented on how-to/use-launch-external-process/public/app.json
> +{
could we rename this manifest.fin.json to be consistent with the others (so it is clear what it is).

2022-04-14 11:11 UTC, johnman commented on how-to/use-launch-external-process/public/app.json
> +        "src": "http://localhost:8080/assets/ProcessExplorer.zip",
Not sure if we should be bundling process explorer. I don't know what the redistribution license is for this. Can we re-use something we have (the winform client or something else). Does this example use app asset and path (e.g. launching notepad)?

2022-04-14 11:11 UTC, johnman commented on how-to/use-launch-external-process/public/serviceworker.js
> +// Mozilla Service Worker Cookbook 'network or cache' recipe: https://serviceworke.rs/strategy-network-or-cache.html
Do we need a service worker for this example? I think we should try keeping that in an offline example in case the service worker has caching issues etc.

2022-04-14 11:11 UTC, johnman commented on how-to/use-launch-external-process/package.json
> +    "openfin-adapter": "^23.67.7",
Can we try using https://www.npmjs.com/package/@openfin/core as it is now released. It would be good to show the new types if we could (and we need to update other projects as well).

2022-04-14 15:38 UTC, adam-saland commented on how-to/add-analytics-to-your-application/advanced/README.md
> +5. Next we need to create a simple index pattern for ElasticSearch, see [here](https://www.elastic.co/guide/en/kibana/current/index-patterns.html) for details. For this example, create an index that
Would you recommend I update?

2022-04-14 15:40 UTC, obany approved these changes

2022-04-14 15:41 UTC, obany commented on how-to/add-analytics-to-your-application/advanced/README.md
> +5. Next we need to create a simple index pattern for ElasticSearch, see [here](https://www.elastic.co/guide/en/kibana/current/index-patterns.html) for details. For this example, create an index that
Might make sense to update, since anybody coming to this now will not find index patterns anymore

2022-04-19 15:01 UTC, adam-saland commented on how-to/add-analytics-to-your-application/advanced/README.md
> +5. Next we need to create a simple index pattern for ElasticSearch, see [here](https://www.elastic.co/guide/en/kibana/current/index-patterns.html) for details. For this example, create an index that
updated with note

2022-05-10 02:51 UTC, adam-saland commented on how-to/use-launch-external-process/public/app.json
> +{
different pr

2022-05-10 02:51 UTC, adam-saland commented on how-to/use-launch-external-process/public/app.json
> +        "src": "http://localhost:8080/assets/ProcessExplorer.zip",
different pr

2022-07-18 15:53 UTC, closed without merging