[CSE-222] how-to/use-popup-window
built-on-openfin/container-starter pull request #21
Opened 2022-05-03 18:47 UTC by connormccafferty

2022-05-06 15:18 UTC, connormccafferty commented on how-to/use-popup-window/multiple-results/client/src/popup.ts
> +    const { customData: contextGroups } = await (fin.me as OpenFin.Window).getOptions();
There is a common set of APIs but there is also Window and View specific methods, e.g. `fin.me.showPopupWindow` is View and Window but `fin.me.dispatchPopupResult` needs `fin as OpenFin.Window` because it's a window-only method.

2022-05-06 15:43 UTC, adam-saland requested changes
just a few suggestions and finds

2022-05-06 15:43 UTC, adam-saland commented on how-to/use-popup-window/advanced/client/src/popup.ts
> +import { fin } from '@openfin/core';;
double semi colon :)

2022-05-06 15:43 UTC, adam-saland commented on how-to/use-popup-window/advanced/client/src/popup.ts
> +
```suggestion
const me  = fin.me as OpenFin.Window;
```

2022-05-06 15:43 UTC, adam-saland commented on how-to/use-popup-window/advanced/client/src/popup.ts
> +        await (fin.me as OpenFin.Window).dispatchPopupResult('confirm');
```suggestion
        await me.dispatchPopupResult('confirm');
```

2022-05-06 15:43 UTC, adam-saland commented on how-to/use-popup-window/advanced/client/src/popup.ts
> +    await fin.me.on('shown', renderShownDate);
```suggestion
    await me.on('shown', renderShownDate);
```

2022-05-06 15:43 UTC, adam-saland commented on how-to/use-popup-window/modal/client/src/popup.ts
> +        await (fin.me as OpenFin.Window).dispatchPopupResult('ok');
same as advanced?

2022-05-06 15:43 UTC, adam-saland commented on how-to/use-popup-window/multiple-results/client/src/popup.ts
> +    const { customData: contextGroups } = await (fin.me as OpenFin.Window).getOptions();
yeah maybe we can set it as a top-level function or file variable. see my comments in advanced and either agree or disagree :)

2022-05-06 15:43 UTC, adam-saland commented on how-to/use-popup-window/single-result/client/src/app.ts
> +    const { top, right, height } = event.target.getBoundingClientRect();
nice! love this :) @connormccafferty clever 😎

2022-05-06 15:43 UTC, adam-saland commented on how-to/use-popup-window/single-result/client/src/popup.ts
> +import { fin } from '@openfin/core';;
;;

2022-05-06 15:43 UTC, adam-saland commented on how-to/use-popup-window/single-result/client/src/popup.ts
> +        await (fin.me as OpenFin.Window).dispatchPopupResult('ok');
same as advanced

2022-05-09 13:32 UTC, adam-saland approved these changes
Looks great!

2022-05-09 14:31 UTC, johnman approved these changes

2022-05-09 15:09 UTC, merged