CSE-268: Add gh actions
built-on-openfin/container-starter pull request #23
Opened 2022-05-17 13:17 UTC by adam-saland

need to make sure git will pick up the .github folder

2022-05-17 13:22 UTC, obany requested changes
We probably also need to add links to all the READMEs to point to the hosted versions

2022-05-17 13:25 UTC, adam-saland commented on scripts/package.js
> +      to: 'https://built-on-openfin.github.io/workspace-starter/' + hostFolder + '/' + package['how-tos'][i],
hahaha yes!

2022-05-17 13:25 UTC, adam-saland commented on scripts/package.js
> +let hostFolder = "workspace/v" + package.version;
lol nope

2022-05-17 13:29 UTC, obany commented on scripts/package.js
> +let hostFolder = "workspace/v" + package.version;
maybe @johnman has some thoughts ?

2022-05-17 13:40 UTC, adam-saland commented
TODO: Add start link to each readme

2022-05-23 13:52 UTC, johnman commented on scripts/package.js
> +let hostFolder = "workspace/v" + package.version;
this was the workspace version (thinking we only wanted to update the urls to point to workspace versions).  Right now we might be able to change this just to main and only support a main branch for publishing. I am having discussions about how to approach container vs workspace when it comes to branch strategy.

2022-05-23 16:37 UTC, johnman requested changes

2022-05-23 16:37 UTC, johnman commented on .github/workflows/.github-actions.yml
> +      - run: npm run package-how-tos
This line can become:

      - run: npm run package-how-tos -- ${{ steps.extract_branch.outputs.branch }}

and it will pass the branch name to the npm package.

2022-05-23 16:37 UTC, johnman commented on scripts/package.js
> +let hostFolder = "container-starter/v" + package.version;
This and line 7 - 9 can be replaced with:

let hostFolder = "main";

if(package.howToCustomFolder !== undefined && package.howToCustomFolder !== ""){
  hostFolder = package.howToCustomFolder;
} else if(process.argv !== undefined && process.argv.length > 2) {
  hostFolder = process.argv[2];
}

console.log('host folder:', hostFolder);

This will let it use the branch name that was passed from the build script unless a custom folder is specified in the package.json

2022-05-23 16:47 UTC, adam-saland commented on package.json
> +        "use-dynamic-manifest/basic",
@johnman @obany should I add a flag: something canHost? Or just ignore it for now?

2022-05-23 17:14 UTC, johnman commented on package.json
> +        "use-dynamic-manifest/basic",
You only include the ones that can be hosted. That way they are the only ones that get built

2022-05-24 06:49 UTC, obany commented on package.json
> +        "use-dynamic-manifest/basic",
if we wanted them all to be built we would be better switching to the workspaces pattern where the package.json just contains `"workspaces": [ "how=to/*"]` instead of `how-to` and then we have a separate `excludeFromHosting` list which the packaing script uses to exclude from the workspaces list.

2022-05-24 07:47 UTC, johnman commented on package.json
> +        "use-dynamic-manifest/basic",
Yeah I think building them all is important and my suggestion would mean not building one (which would be a case of works on my machine). Everything is copied to an output folder so the exclude folder could be used to exclude for that for the folders that can't be hosted. The question is should we get this merged in and working and then refactor to use workspaces (with the goal that you should still be able to build at the folder level).

2022-07-14 02:16 UTC, closed without merging