Use window options
built-on-openfin/container-starter pull request #24
Opened 2022-05-24 10:06 UTC by obany

Example to demonstrate the use of the window options

2022-05-27 12:54 UTC, johnman approved these changes

2022-05-27 14:15 UTC, adam-saland requested changes
Awesome sauce.

2022-05-27 14:15 UTC, adam-saland commented on how-to/use-window-options/public/manifest.fin.json
> +    "version": "stable"
Do we want to put a runtime version in here? I forget how we wanted to approach...

2022-05-27 14:27 UTC, obany commented on how-to/use-window-options/public/manifest.fin.json
> +    "version": "stable"
All the other examples have stable, they should work with most recent versions. Once we have the GH automated builds we will see if stuff breaks

2022-06-09 15:02 UTC, johnman commented on how-to/use-window-options/public/manifest.fin.json
> +    "version": "stable"
lets get this in but then we will do a pass that will pin to the next runtime release (102). And I think maybe we should pick a port as some are 8080 and I think others are 5050. Maybe 5050 so you can run a container sample alongside a workspace starter sample?

2022-06-13 13:11 UTC, merged