update and clean code per new repo features (thanks @martyn :))
built-on-openfin/container-starter pull request #33
Opened 2022-07-11 14:53 UTC by adam-saland

TODO:

- [ ] Default Styles

2022-07-13 07:10 UTC, obany commented on how-to/use-channel-api/issue-commands-to-a-platform/public/html/app.html
> +		<link rel="stylesheet" href="http://localhost:5050/common/style/app.css" />
You should be able to set this to `href="/common/style/app.css` the deployment script will update this accordingly

2022-07-13 07:11 UTC, obany commented on how-to/use-interop/setup-multi-platform-interop/README.md
> +---
Remove `---` separator, not necessary before heading

2022-07-13 07:11 UTC, obany commented on how-to/use-interop/setup-multi-platform-interop/README.md
> +---
Remove `---` separator, not necessary before heading

2022-07-13 07:13 UTC, obany commented on how-to/use-interop/setup-multi-platform-interop/README.md
> +```bash
Markdown shell should be
<pre>
```shell
npm install
```
</pre>
i.e. change bash to shell and remove `$` on command

2022-07-13 07:15 UTC, obany commented on how-to/use-interop/setup-multi-platform-interop/package.json
> +	"license": "ISC",
`license` should be `"license": "SEE LICENSE IN LICENSE.MD"`

Looks like a lot of the other packages need updating too!

2022-07-13 07:16 UTC, obany commented on how-to/use-interop/setup-multi-platform-interop/package.json
> +		"@openfin/core": "latest",
Fix this to specific version

2022-07-13 07:16 UTC, obany commented on how-to/use-interop/setup-multi-platform-interop/package.json
> +		"openfin-adapter": "^25.69.8",
Remove `openfin-adapter`

2022-07-13 07:16 UTC, obany commented on how-to/use-interop/setup-multi-platform-interop/public/html/provider.html
> +<!DOCTYPE html>
Does this need styling ?

2022-07-13 07:17 UTC, obany requested changes
Few minor changes

2022-07-13 16:11 UTC, obany approved these changes

2022-07-14 07:28 UTC, johnman requested changes

2022-07-14 07:29 UTC, johnman commented on how-to/use-interop/setup-multi-platform-interop/README.md
> +```bash
Should this be the new npm run setup command?

2022-07-14 14:34 UTC, obany commented on how-to/use-interop/setup-multi-platform-interop/client/src/window.ts
> +		.classList.remove(
Can we use getContextGroups and loop through them to remove the classes, something like

```
const contextGroups: PlatformContextGroups = await fin.me.interop.getContextGroups();
document
		.querySelector(`#tab-${lastFocusedView.name}`)
		.classList.remove(...contextGroups.map(channel => `${channel.displayMetadata.name}-channel`))
```

2022-07-19 07:22 UTC, obany requested changes
Couple of tweaks, and remove the package-lock.json

2022-07-19 07:22 UTC, obany commented on .eslintrc.js
> +				'@typescript-eslint/dot-notation': ['off'],
This would be better disabled where the fix is required, with a comment as to why if its not self explanatory

2022-07-19 13:42 UTC, obany approved these changes

2022-07-19 14:58 UTC, merged