Add Warn Before Closing Dialog Demo
built-on-openfin/container-starter pull request #40
Opened 2022-07-14 20:55 UTC by luiemilio

2022-07-27 12:05 UTC, johnman requested changes
Hi, thanks for the contributions. Just added a few points to bring it into line with workspace and container starter samples.

2022-07-27 12:05 UTC, johnman commented on how-to/use-platform/warn-before-closing-dialog/public/config/manifest.json
> +{
Can this be renamed to manifest.fin.json and get moved to the root of the public folder to get consistent with workspace starter and container?

2022-07-27 12:05 UTC, johnman commented on how-to/use-platform/warn-before-closing-dialog/public/html/dialog.html
> +    <style>
We now have a common styleguide for starters shared across workspace starter and container starter. Is it possible to use it? E.g. https://github.com/built-on-openfin/container-starter/blob/264e139bd1f653591481848d4137f9ec6f154220/how-to/create-window/public/html/window.html#L8

2022-07-27 12:05 UTC, johnman commented on how-to/use-platform/warn-before-closing-dialog/public/html/provider.html
> +    <meta name="viewport" content="width=device-width, initial-scale=1">
We now have a common styleguide for starters shared across workspace starter and container starter. Is it possible to use it? E.g. https://github.com/built-on-openfin/container-starter/blob/264e139bd1f653591481848d4137f9ec6f154220/how-to/create-window/public/html/window.html#L8

2022-07-27 12:05 UTC, johnman commented on how-to/use-platform/warn-before-closing-dialog/public/html/view.html
> +    <style>
We now have a common styleguide for starters shared across workspace starter and container starter. Is it possible to use it? E.g. https://github.com/built-on-openfin/container-starter/blob/264e139bd1f653591481848d4137f9ec6f154220/how-to/create-window/public/html/window.html#L8

2022-07-27 12:05 UTC, johnman commented on how-to/use-platform/warn-before-closing-dialog/public/html/window.html
> +    <script type="module" src="../js/window.bundle.js"></script>
We now have a common styleguide for starters shared across workspace starter and container starter. Is it possible to use it? E.g. https://github.com/built-on-openfin/container-starter/blob/264e139bd1f653591481848d4137f9ec6f154220/how-to/create-window/public/html/window.html#L8

2022-09-05 10:49 UTC, obany commented on how-to/use-platform/warn-before-closing-dialog/public/html/view.html
> +        <div id="input-div">
Could we use the standard approach for laying out forms, the style.html in common has an example of using fieldsets and labels

2022-09-05 15:22 UTC, johnman approved these changes

2022-09-28 21:09 UTC, adam-saland commented
Need to update to use common fin, will add and merge.

2022-12-05 17:41 UTC, johnman commented
@luiemilio hi Luis. When you have a spare cycle could you re-review this pull request? It would be good to get it in.

2022-12-06 06:03 UTC, adam-saland commented
I think I did this in vnext... may have forgotten to merge

2023-05-25 20:25 UTC, adam-saland commented
resolved in other PR/Branch

2023-05-25 20:25 UTC, closed without merging