Improve the starter consistency
built-on-openfin/container-starter pull request #43
Opened 2022-07-28 12:57 UTC by obany

Minor tweaks to align the different starters

2022-07-29 11:42 UTC, johnman requested changes

2022-07-29 11:42 UTC, johnman commented on how-to/use-interop/setup-multi-platform-interop/README.md
> +npm run client2
should this be run secondclient for consistency?

2022-07-29 11:44 UTC, obany commented on how-to/use-interop/setup-multi-platform-interop/README.md
> +npm run client2
done

2022-08-01 17:37 UTC, johnman approved these changes

2022-08-01 19:55 UTC, merged