Dev/adam/lep
built-on-openfin/container-starter pull request #56
Opened 2022-10-04 13:02 UTC by adam-saland

2022-10-04 15:24 UTC, johnman requested changes
Good stuff. Just a few suggestions.

2022-10-04 15:24 UTC, johnman commented on how-to/use-launch-external-process/client/src/app.ts
> +				console.log("Process Explorer");
Should this log "Process Explorer"? I would expect .NET app xyz

2022-10-04 15:24 UTC, johnman commented on how-to/use-launch-external-process/package.json
> +		"build": "npm run build-server & npm run build-client",
Do we need the dos command here as a shortcut?

2022-10-04 15:24 UTC, johnman commented on how-to/use-launch-external-process/client/src/app.ts
> +		.catch(console.error);
Rather than trigger a launch onload should it be a button (adds something more to the UI) so that they can set a breakpoint and debug if they want without having to try and reload the app?

2022-10-04 16:31 UTC, adam-saland commented on how-to/use-launch-external-process/public/dos.json
> +			"permissions": {
true great catch!

2022-10-04 16:32 UTC, adam-saland commented on how-to/use-launch-external-process/client/src/app.ts
> +				console.log("Process Explorer");
Yup

2022-10-05 06:08 UTC, obany approved these changes

2022-10-05 06:15 UTC, merged