Dev/ameet/automation testing
built-on-openfin/container-starter pull request #64
Opened 2023-01-24 14:05 UTC by ameetj85

Created automation tests for 3 container samples

2023-01-25 05:13 UTC, obany requested changes
A few comments, mostly around things that can be removed

2023-01-25 05:13 UTC, obany commented on .gitignore
> +package-lock.old.json
No need for this in .gitignore

2023-01-25 05:13 UTC, obany commented on how-to/automation-testing/create-window-js/automation-hooks.js
> +exports.setup = async (globalVars) => {
You can remove this file if you are not using hooks

2023-01-25 05:13 UTC, obany commented on how-to/automation-testing/create-window-js/jasmine.reporter.json
> +{
You can remove this file if you are not using jasmine test runner

2023-01-25 05:13 UTC, obany commented on how-to/automation-testing/create-window-js/jest.reporter.json
> +{
You can remove this file if you are not using jest test runner

2023-01-25 05:13 UTC, obany commented on how-to/automation-testing/create-window-js/offline-storage/offline-versions.json
> +{
You can remove this folder if you dont want to run in offline mode

2023-01-25 05:13 UTC, obany commented on how-to/automation-testing/create-window-js/package.json
> +		"jasmine-pretty-html-reporter": "0.2.5",
You can remove jasmine and jest reporters

2023-01-25 05:13 UTC, obany commented on how-to/automation-testing/create-window-js/tests/index.spec.js
> +/* eslint-disable linebreak-style */
We should try not to disable lint rules as the main ones are there for consistency

2023-01-25 05:13 UTC, obany commented on how-to/automation-testing/use-launch-external-process-js/jasmine.reporter.json
> +{
You can remove this file if you are not using jasmine test runner

2023-01-25 05:13 UTC, obany commented on how-to/automation-testing/use-launch-external-process-js/jest.reporter.json
> +{
You can remove this file if you are not using jest test runner

2023-01-25 05:13 UTC, obany commented on how-to/automation-testing/use-launch-external-process-js/package.json
> +		"jasmine-pretty-html-reporter": "0.2.5",
Remove jasmine and jest

2023-01-25 05:13 UTC, obany commented on how-to/automation-testing/use-launch-external-process-js/tests/index.spec.js
> +/* eslint-disable linebreak-style */
Remove eslint disables, fix the code instead

2023-01-25 05:13 UTC, obany commented on how-to/automation-testing/use-window-options-js/automation-hooks.js
> +/* eslint-disable linebreak-style */
Not needed

2023-01-25 05:13 UTC, obany commented on how-to/automation-testing/use-window-options-js/jasmine.reporter.json
> +{
You can remove this file if you are not using jasmine test runner

2023-01-25 05:13 UTC, obany commented on how-to/automation-testing/use-window-options-js/jest.reporter.json
> +{
You can remove this file if you are not using jest test runner

2023-01-25 05:13 UTC, obany commented on how-to/automation-testing/use-window-options-js/offline-storage/offline-versions.json
> +{
Remove offline folder if not running on offline mode

2023-01-25 05:13 UTC, obany commented on how-to/automation-testing/use-window-options-js/package.json
> +		"jasmine-pretty-html-reporter": "0.2.5",
Remove jasmine and jest

2023-01-25 05:13 UTC, obany commented on how-to/automation-testing/use-window-options-js/tests/index.spec.js
> +/* eslint-disable linebreak-style */
Remove disables and fix code instead

2023-01-25 13:58 UTC, johnman reviewed
A few comments in there. Generally we try to use Typescript as the default. Was JS used to make it easier for the person reading it (as it is a small test file)?

The examples use xpath and paths. We should note in the readme that this is a basic example and link to other approaches such as the page model for them to consider: https://www.selenium.dev/documentation/test_practices/encouraged/page_object_models/

2023-01-25 13:58 UTC, johnman commented on how-to/automation-testing/create-window-js/automation-hooks.js
> +	// console.log("Before", currentTestName);
Could we remove the commented out code or uncomment it?

2023-01-25 13:58 UTC, johnman commented on how-to/automation-testing/create-window-js/tests/index.spec.js
> +		expect(version).to.equal('26.102.70.16');
Should we pull this from the manifest if we have the fin api? That way the runtime version isn't hardcoded and isn't something we will miss in the future?

2023-01-25 13:58 UTC, johnman commented on how-to/automation-testing/use-launch-external-process-js/automation-hooks.js
> +	// console.log("Before", currentTestName);
Same as before. Can we uncomment or remove?

2023-01-25 13:58 UTC, johnman commented on how-to/automation-testing/use-launch-external-process-js/tests/index.spec.js
> +		expect(version).to.equal('26.102.71.7');
Maybe we should pull the current version from the manifest so it isn't something we have to maintain?

2023-01-25 13:58 UTC, johnman commented on how-to/automation-testing/use-window-options-js/automation-hooks.js
> +	// console.log("Before", currentTestName);
remove commented out code or uncomment?

2023-01-25 13:58 UTC, johnman commented on how-to/automation-testing/use-window-options-js/tests/index.spec.js
> +		expect(version).to.equal('26.102.70.16');
should we read the version from the manifest?

2023-01-25 13:58 UTC, ameetj85 commented on how-to/automation-testing/create-window-js/automation-hooks.js
> +exports.setup = async (globalVars) => {
Strange but I dont see that in .gitignore. The only entries that I have are: 
chromedriver/
reports/
screenshots/

2023-01-25 13:59 UTC, ameetj85 commented on .gitignore
> +package-lock.old.json
Strange but I dont see that in .gitignore. The only entries that I have are:
chromedriver/
reports/
screenshots/

2023-01-26 05:33 UTC, obany commented on how-to/automation-testing/create-window-js/tests/index.spec.js
> +/* eslint linebreak-style: ["error", "windows"] */
There is a setting for git and vscode to make sure this works without needing the eslint rule

2023-01-28 03:46 UTC, adam-saland commented on how-to/automation-testing/create-window-js/tests/index.spec.js
> +/* eslint linebreak-style: ["error", "windows"] */
@obany / @johnman should we add to validate or is only relevant to test framework syntax validation?

2023-01-30 06:15 UTC, obany commented on how-to/automation-testing/create-window-js/tests/index.spec.js
> +/* eslint linebreak-style: ["error", "windows"] */
So this is just a setting needed for git commits https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings
It just keeps all the code consistent with line endings, which is why the eslint rule is enabled, if you need to disable the rule means your git config is incorrect

2023-02-08 09:38 UTC, obany commented on .gitignore
> +package-lock.old.json
It the .gitignore in the root of the repo

2023-02-22 01:54 UTC, ameetj85 commented on .gitignore
> +package-lock.old.json
Done

2023-02-22 05:22 UTC, obany requested changes

2023-02-22 05:22 UTC, obany commented on how-to/automation-testing/create-window-js/package.json
> +		"setup": "cd ../../../ && npm install && cd how-to/use-a-manifest/create-a-single-page-platform && npm run build",
The setup command has the wrong path

2023-02-22 05:22 UTC, obany commented on how-to/automation-testing/.vscode/settings.json
> +{
This file should not be necessary, if you really want these options, then you can add them to your global vscode config

2023-02-22 05:22 UTC, obany commented on how-to/automation-testing/use-launch-external-process-js/package.json
> +		"setup": "cd ../../../ && npm install && cd how-to/use-a-manifest/create-a-single-page-platform && npm run build",
The setup command has the wrong path

2023-02-22 05:22 UTC, obany commented on how-to/automation-testing/use-window-options-js/package.json
> +		"setup": "cd ../../../ && npm install && cd how-to/use-a-manifest/create-a-single-page-platform && npm run build",
The setup command has the wrong path

2023-02-22 11:29 UTC, obany approved these changes

2023-02-23 14:53 UTC, merged